monsieurbiz_case_study_shop:
    resource: '@MonsieurBizSyliusCaseStudyPlugin/Resources/config/routes/shop.yaml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$


monsieurbiz_case_study_admin:
    resource: '@MonsieurBizSyliusCaseStudyPlugin/Resources/config/routes/admin.yaml'
    prefix: '/%sylius_admin.path_name%'
