monsieurbiz_robots_txt_render:
    path: /robots.txt
    methods: [ GET ]
    defaults:
        _controller: MonsieurBiz\SyliusRobotsTxtPlugin\Controller\RenderController
        settingName: 'robots_txt_content'
monsieurbiz_llms_txt_render:
    path: /llms.txt
    methods: [ GET ]
    defaults:
        _controller: MonsieurBiz\SyliusRobotsTxtPlugin\Controller\RenderController
        settingName: 'llms_txt_content'
