sylius_shop_contact_request:
    path: /{_locale}/contact
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop.contact::requestAction
        _sylius:
            redirect: sylius_shop_homepage
            template: '@MonsieurBizSyliusContactRequestPlugin/Shop/ContactRequest/request.html.twig'
